# Generated by Django 3.1.7 on 2022-01-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_passby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
    ]
